-- TABLE ENDEREÇO E SUAS CONSTRAINTS
DROP TABLE UNIDADE;
CREATE TABLE ESCOLAR.UNIDADE( cd_escola    NUMBER NOT NULL,
                              nm_escola    VARCHAR2(255) NOT NULL,
                              CNPJ         NUMBER(14) NOT NULL,
                              cd_endereco  NUMBER NOT NULL,
                              cd_turma     NUMBER NOT NULL,
                              dt_inscricao DATE DEFAULT SYSDATE,
                              sn_ativa     VARCHAR2(1) DEFAULT 'S' NOT NULL
                              );
SELECT * FROM UNIDADE;
ALTER TABLE ESCOLAR.UNIDADE ADD CONSTRAINT PK_UNIDADE_CD_ESCOLA PRIMARY KEY (CD_ESCOLA);
ALTER TABLE ESCOLAR.UNIDADE ADD CONSTRAINT FK_ENDERECO_CD_ENDERECO FOREIGN KEY (CD_ENDERECO) REFERENCES ESCOLAR.ENDERECO (CD_ENDERECO);
ALTER TABLE ESCOLAR.UNIDADE ADD CONSTRAINT FK_TURMA_CD_TURMA FOREIGN KEY (CD_TURMA) REFERENCES ESCOLAR.TURMA(CD_TURMA);
CREATE SEQUENCE escolar.seq_unidade INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 NOCACHE NOCYCLE;

INSERT INTO ESCOLAR.UNIDADE(CD_ESCOLA,NM_ESCOLA,CNPJ,CD_ENDERECO, CD_TURMA,SN_ATIVA )VALUES(SEQ_UNIDADE.NEXTVAL, 'ESCOLA TESTE',987654, 1,1,'N' );

-- TABLE ENDEREÇO E SUAS CONSTRAINTS
CREATE TABLE ESCOLAR.ENDERECO(cd_endereco NUMBER NOT NULL,
                             rua         VARCHAR2(255),
                             bairro      VARCHAR2(255),
                             cidade      VARCHAR2(255),
                             uf          VARCHAR2(2),
                             cep         VARCHAR2(9)
                             );

SELECT * FROM ESCOLAR.ENDERECO;
ALTER TABLE ESCOLAR.ENDERECO ADD CONSTRAINT PK_ENDERECO_CD_ENDERECO PRIMARY KEY (CD_ENDERECO);


INSERT INTO ESCOLAR.ENDERECO(CD_ENDERECO,RUA, BAIRRO, CIDADE, UF,CEP  )VALUES(1, 'RUA TESTE','BAIRRO TESTE','CIDADE TESTE','UF','12345' );

-- TABLE TURMA E SUAS CONSTRAINTS

CREATE TABLE ESCOLAR.TURMA(cd_turma      NUMBER NOT NULL,
                          cd_matricula  NUMBER NOT NULL,
                          cd_tutor      NUMBER NOT NULL,
                          cd_discp      NUMBER NOT NULL
                          );
                          ALTER TABLE ESCOLAR.TURMA RENAME COLUMN CD_DISCP TO CD_DISCIPLINA;
                          ALTER TABLE ESCOLAR.TURMA DROP COLUMN CD_DISCIPLINA;
                          ALTER TABLE ESCOLAR.TURMA ADD CD_DISCIPLINA NUMBER NOT NULL;

SELECT * FROM ESCOLAR.TURMA;
ALTER TABLE ESCOLAR.TURMA ADD CONSTRAINT PK_TURMA_CD_TURMA PRIMARY KEY (CD_TURMA);
ALTER TABLE ESCOLAR.TURMA ADD CONSTRAINT FK_MATRICULA_CD_MATRICULA FOREIGN KEY (CD_MATRICULA) REFERENCES ESCOLAR.MATRICULA(CD_MATRICULA);
ALTER TABLE ESCOLAR.TURMA ADD CONSTRAINT FK_TUTOR_CD_TUTOR FOREIGN KEY (CD_TUTOR) REFERENCES ESCOLAR.TUTOR(CD_TUTOR);
ALTER TABLE ESCOLAR.TURMA ADD CONSTRAINT FK_DICIPLINA_CD_DICIPLINA FOREIGN KEY (CD_DISCIPLINA) REFERENCES ESCOLAR.DICIPLINA(CD_DICIPLINA);

INSERT INTO ESCOLAR.TURMA(CD_TURMA,CD_MATRICULA,CD_TUTOR, CD_DISCIPLINA   )VALUES(1,1,1,1 );


-- TABLE MATRICULO & CONSTRAINTS

CREATE TABLE ESCOLAR.MATRICULA(cd_matricula NUMBER NOT NULL,
                               cd_aluno NUMBER NOT NULL,
                               dt_matricula DATE DEFAULT SYSDATE
                               );
                               SELECT * FROM MATRICULA;

ALTER TABLE escolar.matricula ADD CONSTRAINT pk_matricula_cd_matricula PRIMARY KEY (cd_matricula);
ALTER TABLE ESCOLAR.MATRICULA ADD CONSTRAINT FK_MATRICULA_CD_ALUNO FOREIGN KEY (CD_ALUNO) REFERENCES ESCOLAR.ALUNO(CD_ALUNO);

 INSERT INTO ESCOLAR.MATRICULA(CD_MATRICULA,CD_ALUNO)VALUES(1,1 );

-- TABLE ALUNO & CONSTRAINT
CREATE TABLE ESCOLAR.ALUNO( CD_ALUNO NUMBER NOT NULL,
                            NM_ALUNO VARCHAR2(100) NOT NULL,
                            SH_ALUNO VARCHAR2(10) NOT NULL,
                            CPF_ALUNO NUMBER(11) NULL,
                            DT_NASC_ALUNO DATE NULL,
                            CD_ENDERECOO NUMBER NOT NULL
                            );

                            SELECT * FROM ALUNO;
                            ALTER TABLE ESCOLAR.ALUNO RENAME COLUMN CD_ENDERECOO TO CD_ENDERECO;

ALTER TABLE ESCOLAR.ALUNO ADD CONSTRAINT PK_ALUNO_CD_ALUNO PRIMARY KEY (CD_ALUNO);
ALTER TABLE ESCOLAR.ALUNO ADD CONSTRAINT FK_ALUNO_CD_ENDERECO FOREIGN KEY(CD_ENDERECO) REFERENCES ESCOLAR.ENDERECO (CD_ENDERECO);

INSERT INTO ESCOLAR.ALUNO(CD_ALUNO,CD_ENDERECO,NM_ALUNO, SH_ALUNO, CPF_ALUNO)VALUES(1,1,'Aluno teste','senhateste', 12345 );

-- TABLE TUTOR & CONSTRAINT
 CREATE TABLE ESCOLAR.TUTOR(CD_TUTOR NUMBER NOT NULL,
                            NM_TUTOR VARCHAR2(100) NOT NULL,
                            SH_TUTOR VARCHAR2(10)NOT NULL,
                            CPF_TUTOR NUMBER(11) NOT NULL,
                            DT_NASC_TUTOR DATE NULL,
                            FONE_TUTOR NUMBER(10) NULL,
                            CD_ENDERECO NUMBER NOT NULL);

ALTER TABLE ESCOLAR.TUTOR ADD CONSTRAINT PK_TUTOR_CD_TUTOR PRIMARY KEY (CD_tutor);
ALTER TABLE ESCOLAR.TUTOR ADD CONSTRAINT FK_TUTOR_CD_ENDERECO FOREIGN KEY(CD_ENDERECO) REFERENCES ESCOLAR.ENDERECO (CD_ENDERECO);

INSERT INTO ESCOLAR.TUTOR(CD_TUTOR,CD_ENDERECO,NM_TUTOR, SH_TUTOR, CPF_TUTOR)VALUES(1,1,'Aluno teste','senhateste', 5432 );

             SELECT * FROM TUTOR;

  -- TABLE DISCIPLINA & CONSTRAINT
 CREATE TABLE ESCOLAR.DICIPLINA (CD_DICIPLINA NUMBER NOT NULL,
                                 NM_MATERIA VARCHAR2(255) NOT NULL,
                                 CD_TUTOR NUMBER NOT NULL,
                                 CD_NOTAS NUMBER NOT NULL
                                 );
                                 SELECT * FROM DICIPLINA;

ALTER TABLE ESCOLAR.DICIPLINA ADD CONSTRAINT PK_DICIPLINA_CD_DICIPLINA PRIMARY KEY (CD_DICIPLINA);
ALTER TABLE ESCOLAR.DICIPLINA ADD CONSTRAINT FK_DICIPLINA_CD_TUTOR FOREIGN KEY (CD_TUTOR) REFERENCES ESCOLAR.TUTOR(CD_TUTOR);
ALTER TABLE ESCOLAR.DICIPLINA ADD CONSTRAINT FK_DICIPLINA_CD_NOTAS FOREIGN KEY (CD_NOTAS) REFERENCES ESCOLAR.NOTAS(CD_NOTAS);

INSERT INTO ESCOLAR.DICIPLINA(CD_DICIPLINA,CD_TUTOR,CD_NOTAS,NM_MATERIA)VALUES(1,1,1,'MATERIA teste');

   -- TABLE NOTAS & CONSTRAINT
 CREATE TABLE ESCOLAR.NOTAS (CD_NOTAS NUMBER NOT NULL,
                             CD_ALUNO NUMBER NOT NULL,
                             FINAL NUMBER NULL,
                             RECUPERACAO NUMBER NULL,
                             N1 NUMBER NULL,
                             N2 NUMBER NULL,
                             N3 NUMBER NULL,
                             N4 NUMBER NULL
                               );
                               SELECT * FROM NOTAS;
ALTER TABLE ESCOLAR.NOTAS ADD CONSTRAINT PK_NOTAS_CD_NOTAS PRIMARY KEY (CD_NOTAS);
ALTER TABLE ESCOLAR.NOTAS ADD CONSTRAINT FK_NOTAS_CD_ALUNO FOREIGN KEY (CD_ALUNO) REFERENCES ESCOLAR.ALUNO(CD_ALUNO);

INSERT INTO ESCOLAR.NOTAS(CD_NOTAS,CD_ALUNO,FINAL, RECUPERACAO, N1, N2, N3, N4)VALUES(1,1,1,1,1,1,1,1);





commit;

-- TESTES


SELECT *
FROM ESCOLAR.UNIDADE U, ESCOLAR.ENDERECO E
WHERE U.CD_ENDERECO=E.CD_ENDERECO
AND SN_ATIVA ='N';
               SELECT * FROM NOTAS;
               SELECT * FROM ALUNO;
SELECT *
FROM ALUNO A, NOTAS N
WHERE A.CD_ALUNO = N.CD_NOTAS;